# Generated by Django 4.2.4 on 2023-08-20 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0002_elevationmap_globalelevationmap_nnmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reliefmap",
            name="elev_id",
        ),
        migrations.RemoveField(
            model_name="reliefmap",
            name="model_id",
        ),
        migrations.RemoveField(
            model_name="reliefmap",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="ElevationMap",
        ),
        migrations.DeleteModel(
            name="GlobalElevationMap",
        ),
        migrations.DeleteModel(
            name="NNModel",
        ),
        migrations.DeleteModel(
            name="ReliefMap",
        ),
    ]
