# Generated by Django 4.2.3 on 2023-08-27 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_alter_customuser_email_alter_customuser_ot_token_and_more"),
        ("Users", "0003_remove_reliefmap_elev_id_remove_reliefmap_model_id_and_more"),
    ]

    operations = []
