# Generated by Django 4.2.3 on 2023-08-29 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0006_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="User",
        ),
    ]
