# Generated by Django 4.2.3 on 2023-08-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0007_rename_customuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("credits", models.IntegerField(default=0)),
                ("ot_token", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="elevationmap",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.customuser"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.customuser"
            ),
        ),
        migrations.AlterField(
            model_name="reliefmap",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.customuser"
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
