# Generated by Django 4.2.3 on 2023-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0009_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevationmap",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="elevationmap",
            name="map_ot_id",
        ),
        migrations.RemoveField(
            model_name="elevationmap",
            name="ot_id",
        ),
        migrations.AddField(
            model_name="elevationmap",
            name="file_path",
            field=models.FilePathField(default="test.tif"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="elevationmap",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="elevationmap",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payments",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="GlobalElevationMap",
        ),
    ]
