# Generated by Django 4.2.3 on 2023-10-02 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0010_remove_elevationmap_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reliefmap",
            name="model_id",
        ),
    ]
