# Generated by Django 4.2.3 on 2023-10-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0011_remove_reliefmap_model_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevationmap",
            name="file_path",
            field=models.TextField(),
        ),
    ]
