# Generated by Django 4.2.3 on 2023-10-06 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0012_alter_elevationmap_file_path"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NNModel",
        ),
    ]
