# Generated by Django 4.2.3 on 2023-10-09 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0013_delete_nnmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reliefmap",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
