# Generated by Django 4.2.3 on 2023-10-11 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0014_alter_reliefmap_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="amount",
        ),
    ]
